/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant.repos;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;

/**
 *
 * @author Arima
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    int xMouse, yMouse;
    public Home() {
        initComponents();
        
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        Principal p1 = new Principal();
        p1.setSize(800, 550);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGraund = new javax.swing.JPanel();
        jbarlat = new javax.swing.JPanel();
        txtrest = new javax.swing.JLabel();
        btnCom = new javax.swing.JPanel();
        txtcomanda = new javax.swing.JLabel();
        iconcomanda = new javax.swing.JLabel();
        btnProv = new javax.swing.JPanel();
        txtprov = new javax.swing.JLabel();
        iconprov = new javax.swing.JLabel();
        btnEmp = new javax.swing.JPanel();
        txtEmp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnclear = new javax.swing.JPanel();
        btnInv = new javax.swing.JPanel();
        txtinv = new javax.swing.JLabel();
        iconinv = new javax.swing.JLabel();
        btnPrin = new javax.swing.JPanel();
        txtPrin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jmouse = new javax.swing.JPanel();
        Leave = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        Jtime = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGraund.setBackground(new java.awt.Color(255, 255, 255));
        BackGraund.setPreferredSize(new java.awt.Dimension(650, 450));
        BackGraund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbarlat.setBackground(new java.awt.Color(13, 71, 161));
        jbarlat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtrest.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        txtrest.setForeground(new java.awt.Color(255, 255, 255));
        txtrest.setText("RESTAURANTE");
        jbarlat.add(txtrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 37, -1, -1));

        btnCom.setBackground(new java.awt.Color(18, 90, 173));
        btnCom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnComMousePressed(evt);
            }
        });

        txtcomanda.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtcomanda.setForeground(new java.awt.Color(255, 255, 255));
        txtcomanda.setText("COMANDA");

        iconcomanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/carro.png"))); // NOI18N

        javax.swing.GroupLayout btnComLayout = new javax.swing.GroupLayout(btnCom);
        btnCom.setLayout(btnComLayout);
        btnComLayout.setHorizontalGroup(
            btnComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconcomanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcomanda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnComLayout.setVerticalGroup(
            btnComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconcomanda)
                    .addComponent(txtcomanda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbarlat.add(btnCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, -1));

        btnProv.setBackground(new java.awt.Color(18, 90, 173));
        btnProv.setEnabled(false);
        btnProv.setPreferredSize(new java.awt.Dimension(0, 36));
        btnProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProvMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProvMousePressed(evt);
            }
        });

        txtprov.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtprov.setForeground(new java.awt.Color(255, 255, 255));
        txtprov.setText("PROVEEDORES");

        iconprov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona.png"))); // NOI18N

        javax.swing.GroupLayout btnProvLayout = new javax.swing.GroupLayout(btnProv);
        btnProv.setLayout(btnProvLayout);
        btnProvLayout.setHorizontalGroup(
            btnProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProvLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconprov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtprov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnProvLayout.setVerticalGroup(
            btnProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconprov)
                    .addComponent(txtprov))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbarlat.add(btnProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, -1));

        btnEmp.setBackground(new java.awt.Color(18, 90, 173));
        btnEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmp.setPreferredSize(new java.awt.Dimension(0, 36));
        btnEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpMousePressed(evt);
            }
        });

        txtEmp.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtEmp.setForeground(new java.awt.Color(255, 255, 255));
        txtEmp.setText("EMPLEADOS");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/empleados.png"))); // NOI18N

        javax.swing.GroupLayout btnEmpLayout = new javax.swing.GroupLayout(btnEmp);
        btnEmp.setLayout(btnEmpLayout);
        btnEmpLayout.setHorizontalGroup(
            btnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmpLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmp)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        btnEmpLayout.setVerticalGroup(
            btnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEmpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmp)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jbarlat.add(btnEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, -1));

        btnclear.setBackground(new java.awt.Color(18, 90, 173));
        btnclear.setPreferredSize(new java.awt.Dimension(0, 36));

        javax.swing.GroupLayout btnclearLayout = new javax.swing.GroupLayout(btnclear);
        btnclear.setLayout(btnclearLayout);
        btnclearLayout.setHorizontalGroup(
            btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnclearLayout.setVerticalGroup(
            btnclearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jbarlat.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, -1));

        btnInv.setBackground(new java.awt.Color(18, 90, 173));
        btnInv.setPreferredSize(new java.awt.Dimension(0, 36));
        btnInv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInvMousePressed(evt);
            }
        });

        txtinv.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtinv.setForeground(new java.awt.Color(255, 255, 255));
        txtinv.setText("INVENTARIO");

        iconinv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lista-de-verificacion .png"))); // NOI18N

        javax.swing.GroupLayout btnInvLayout = new javax.swing.GroupLayout(btnInv);
        btnInv.setLayout(btnInvLayout);
        btnInvLayout.setHorizontalGroup(
            btnInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInvLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iconinv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtinv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInvLayout.setVerticalGroup(
            btnInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInvLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(btnInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtinv)
                    .addComponent(iconinv))
                .addGap(2, 2, 2))
        );

        jbarlat.add(btnInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, -1));

        btnPrin.setBackground(new java.awt.Color(21, 101, 192));
        btnPrin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrin.setPreferredSize(new java.awt.Dimension(0, 36));
        btnPrin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrinMousePressed(evt);
            }
        });

        txtPrin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtPrin.setForeground(new java.awt.Color(255, 255, 255));
        txtPrin.setText("INICIO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hogar.png"))); // NOI18N

        javax.swing.GroupLayout btnPrinLayout = new javax.swing.GroupLayout(btnPrin);
        btnPrin.setLayout(btnPrinLayout);
        btnPrinLayout.setHorizontalGroup(
            btnPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrin)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        btnPrinLayout.setVerticalGroup(
            btnPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPrinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtPrin))
                .addContainerGap())
        );

        jbarlat.add(btnPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(0.7F);
        jSeparator1.setAlignmentY(0.7F);
        jbarlat.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 220, 19));

        BackGraund.add(jbarlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 640));

        jmouse.setBackground(new java.awt.Color(255, 255, 255));
        jmouse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jmouseMouseDragged(evt);
            }
        });
        jmouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmouseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jmouseLayout = new javax.swing.GroupLayout(jmouse);
        jmouse.setLayout(jmouseLayout);
        jmouseLayout.setHorizontalGroup(
            jmouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jmouseLayout.setVerticalGroup(
            jmouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        BackGraund.add(jmouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 0, 740, 30));

        Leave.setBackground(new java.awt.Color(255, 255, 255));
        Leave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LeaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LeaveMouseExited(evt);
            }
        });

        txtExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtExit.setText("X");

        javax.swing.GroupLayout LeaveLayout = new javax.swing.GroupLayout(Leave);
        Leave.setLayout(LeaveLayout);
        LeaveLayout.setHorizontalGroup(
            LeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeaveLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtExit)
                .addGap(20, 20, 20))
        );
        LeaveLayout.setVerticalGroup(
            LeaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        BackGraund.add(Leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 50, 30));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        BackGraund.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 800, 550));

        Jtime.setBackground(new java.awt.Color(255, 255, 255));

        fecha.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        fecha.setText("Hoy es Lunes 7 de Noviembre del 2022");

        javax.swing.GroupLayout JtimeLayout = new javax.swing.GroupLayout(Jtime);
        Jtime.setLayout(JtimeLayout);
        JtimeLayout.setHorizontalGroup(
            JtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JtimeLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(fecha)
                .addGap(252, 252, 252))
        );
        JtimeLayout.setVerticalGroup(
            JtimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JtimeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackGraund.add(Jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 800, 40));

        getContentPane().add(BackGraund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComMouseClicked

    private void LeaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaveMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LeaveMouseClicked

    private void LeaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaveMouseEntered
        // TODO add your handling code here:
        Leave.setBackground(Color.red);
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_LeaveMouseEntered

    private void LeaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaveMouseExited
        // TODO add your handling code here:
        Leave.setBackground(Color.white);
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_LeaveMouseExited

    private void jmouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmouseMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jmouseMousePressed

    private void jmouseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmouseMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse );
    }//GEN-LAST:event_jmouseMouseDragged

    private void btnComMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComMouseEntered
        // TODO add your handling code here:
        if(btnCom.getBackground().getRGB() == -15574355)
            setColor(btnCom);
    }//GEN-LAST:event_btnComMouseEntered

    private void btnComMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComMouseExited
        // TODO add your handling code here:
        if(btnPrin.getBackground().getRGB() != -15574355 || btnProv.getBackground().getRGB() != -15574355 || btnInv.getBackground().getRGB() != -15574355)
            resetColor(btnCom);
    }//GEN-LAST:event_btnComMouseExited

    private void btnProvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvMouseEntered
        // TODO add your handling code here:
        if(btnProv.getBackground().getRGB() == -15574355)
            setColor(btnProv);
    }//GEN-LAST:event_btnProvMouseEntered

    private void btnProvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvMouseExited
        // TODO add your handling code here:
        if(btnCom.getBackground().getRGB() != -15574355 || btnPrin.getBackground().getRGB() != -15574355 || btnInv.getBackground().getRGB() != -15574355)
            resetColor(btnProv);
    }//GEN-LAST:event_btnProvMouseExited

    private void btnComMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComMousePressed
        resetColor(btnPrin);
        setColor(btnCom);
        resetColor(btnProv);
        resetColor(btnInv);
        resetColor(btnEmp);
        //Seleccion de Area
        Comanda1 com = new Comanda1();
        com.setSize(800,550);
        com.setLocation(0,0);
        
        content.removeAll();
        content.add(com, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnComMousePressed

    private void btnProvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvMousePressed
        resetColor(btnPrin);
        resetColor(btnCom);
        setColor(btnProv);
        resetColor(btnInv);
        //seleccion de area
        Proveedores prov = new Proveedores();
        prov.setSize(800,550);
        prov.setLocation(0,0);
        
        content.removeAll();
        content.add(prov, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnProvMousePressed

    private void btnInvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvMouseEntered
        // TODO add your handling code here:
        if(btnInv.getBackground().getRGB() == -15574355)
            setColor(btnInv);
    }//GEN-LAST:event_btnInvMouseEntered

    private void btnInvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvMouseExited
        // TODO add your handling code here:
        if(btnCom.getBackground().getRGB() != -15574355 || btnPrin.getBackground().getRGB() != -15574355 || btnCom.getBackground().getRGB() != -15574355)
            resetColor(btnInv);
    }//GEN-LAST:event_btnInvMouseExited

    private void btnInvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvMousePressed
        resetColor(btnPrin);
        resetColor(btnCom);
        resetColor(btnProv);
        resetColor(btnEmp);
        setColor(btnInv);
        
        //Seleccion de Area
        Inventario Inv = new Inventario();
        Inv.setSize(800,550);
        Inv.setLocation(0,0);
        
        content.removeAll();
        content.add(Inv, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnInvMousePressed

    private void btnPrinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinMousePressed
        setColor(btnPrin);
        resetColor(btnCom);
        resetColor(btnProv);
        resetColor(btnInv);
        resetColor(btnEmp);
        //seleccion de area
        Principal p1 = new Principal();
        p1.setSize(800, 550);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_btnPrinMousePressed

    private void btnPrinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinMouseEntered
        // TODO add your handling code here:
        if(btnPrin.getBackground().getRGB() == -15574355)
            setColor(btnPrin);
    }//GEN-LAST:event_btnPrinMouseEntered

    private void btnPrinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrinMouseExited
        // TODO add your handling code here:
        if(btnCom.getBackground().getRGB() != -15574355 || btnProv.getBackground().getRGB() != -15574355 || btnInv.getBackground().getRGB() != -15574355)
            resetColor(btnPrin);
    }//GEN-LAST:event_btnPrinMouseExited

    private void btnEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpMouseEntered
        // TODO add your handling code here:
        if(btnEmp.getBackground().getRGB() == -15574355)
            setColor(btnEmp);
    }//GEN-LAST:event_btnEmpMouseEntered

    private void btnEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpMouseExited
        // TODO add your handling code here:
        if(btnCom.getBackground().getRGB() != -15574355 || btnPrin.getBackground().getRGB() != -15574355 || btnCom.getBackground().getRGB() != -15574355)
            resetColor(btnEmp);
    }//GEN-LAST:event_btnEmpMouseExited

    private void btnEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpMousePressed
        // TODO add your handling code here:
        resetColor(btnPrin);
        resetColor(btnCom);
        resetColor(btnProv);
        resetColor(btnInv);
        setColor(btnEmp);
        //Seleccion de Area
        Empleados emp = new Empleados();
        emp.setSize(800,550);
        emp.setLocation(0,0);
        
        content.removeAll();
        content.add(emp, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnEmpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGraund;
    private javax.swing.JPanel Jtime;
    private javax.swing.JPanel Leave;
    private javax.swing.JPanel btnCom;
    private javax.swing.JPanel btnEmp;
    private javax.swing.JPanel btnInv;
    private javax.swing.JPanel btnPrin;
    private javax.swing.JPanel btnProv;
    private javax.swing.JPanel btnclear;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel iconcomanda;
    private javax.swing.JLabel iconinv;
    private javax.swing.JLabel iconprov;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jbarlat;
    private javax.swing.JPanel jmouse;
    private javax.swing.JLabel txtEmp;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtPrin;
    private javax.swing.JLabel txtcomanda;
    private javax.swing.JLabel txtinv;
    private javax.swing.JLabel txtprov;
    private javax.swing.JLabel txtrest;
    // End of variables declaration//GEN-END:variables
}
