/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurant.repos;

import SQLConexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Arima
 */
public class Proveedores extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores
     */
    
 Conexion cc = new Conexion();
Connection con = cc.conexion();
PreparedStatement ps;
ResultSet rs;
Statement st;
    public Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNlegal = new javax.swing.JTextField();
        txtNcom = new javax.swing.JTextField();
        txtMatprim = new javax.swing.JTextField();
        txtCporU = new javax.swing.JTextField();
        txtPrecioU = new javax.swing.JTextField();
        txtPrecioT = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre Legal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel3.setText("Nombre Comercial:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel4.setText("Materia Prima:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel5.setText("Cantidad por Unidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel6.setText("Precio Unitario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel7.setText("Precio Total:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));
        jPanel1.add(txtNlegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 220, -1));
        jPanel1.add(txtNcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 220, -1));
        jPanel1.add(txtMatprim, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 220, -1));
        jPanel1.add(txtCporU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 220, -1));
        jPanel1.add(txtPrecioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 220, -1));
        jPanel1.add(txtPrecioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 220, -1));
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 220, -1));

        jPanel2.setBackground(new java.awt.Color(18, 90, 173));
        jPanel2.setPreferredSize(new java.awt.Dimension(111, 29));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jPanel3.setBackground(new java.awt.Color(18, 90, 173));
        jPanel3.setPreferredSize(new java.awt.Dimension(111, 29));

        jLabel9.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        jPanel4.setBackground(new java.awt.Color(18, 90, 173));
        jPanel4.setPreferredSize(new java.awt.Dimension(111, 29));

        jLabel10.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        jPanel5.setBackground(new java.awt.Color(18, 90, 173));
        jPanel5.setPreferredSize(new java.awt.Dimension(111, 29));

        jLabel11.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 550));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 220, -1));

        jLabel12.setText("Identificador:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1729, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // Funcion de insertado de datos
        int fila=Table.getSelectedRow();
        if (fila ==-1){
            JOptionPane.showMessageDialog(null, "Fila no Seleccionada");
        }else{
            String NomL=(String)Table.getValueAt(fila, 0);
            String NomC=(String)Table.getValueAt(fila, 1);
            String MatP=(String)Table.getValueAt(fila, 2);
            String CporU=(String)Table.getValueAt(fila, 3);
            String PrecioU=(String)Table.getValueAt(fila, 4);
            
            //Mandamos a llamar a las variables
            txtNlegal.setText(""+NomL);
            txtNcom.setText(""+NomC);
            txtMatprim.setText(""+MatP);
            txtCporU.setText(""+CporU);
            txtPrecioU.setText(""+PrecioU);
            //txtPrecioT.setText();
            //txtTel.setText();
        }
    }//GEN-LAST:event_TableMouseClicked

    //Metodos
    
     public void eliminarRegistro(){
        int filaSeleccionada = Table.getSelectedRow();
        try{
            String SQL = "delete from provedores where ID="+Table.getValueAt(filaSeleccionada,0);
            Statement st = con.createStatement();
            int n = st.executeUpdate(SQL);
            if (n>=0){
                 JOptionPane.showMessageDialog(null, "Registro eliminado");
            }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Error de eliminacion "+ e.getMessage());
        }
    }
    public void limpiarCajas(){
   
    txtID.setText("");
    txtNcom.setText("");
    txtMatprim.setText("");
    txtCporU.setText("");
    txtPrecioU.setText("");
    txtPrecioT.setText("");
    txtTel.setText("");
}

        public void insertarDatos(){
        String SQL = "insert into proveedores (ID,Nombre_legal,Nombre_comercial, Materia_prima, Precio_unitario, Precio_total,Telefono,) values(?,?,?,?,?,?,?,?)";    
        try{
        ps = con.prepareStatement(SQL);        
//PreparedStatement pst = con.prepareStatement(SQL);
        //Envia lo que se ingresa en el cuadro de texto
        ps.setString(1, txtID.getText());
        ps.setString(2, txtNcom.getText());
        ps.setString(3, txtMatprim.getText());
        ps.setString(4, txtCporU.getText());
        ps.setString(5, txtPrecioU.getText());
        ps.setString(6, txtPrecioT.getText());
        ps.setString(7, txtTel.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Registro excitoso");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error de Registro  " +e.getMessage());
    }
}
  
        public void actualizarDatos(){
     String SQL = "update proveedores set  Nombre=?,Apellido_P=?,Apellido_M=?,Telefono=?,Direccion=?,ID_Puesto=? where ID=?";
    try{
       ps = con.prepareStatement(SQL);

        //Envia lo que se ingresa en el cuadro de texto
        ps.setString(1, txtNcom.getText());
        ps.setString(2, txtMatprim.getText());
        ps.setString(3, txtCporU.getText());
        ps.setString(4,txtPrecioU.getText());
        ps.setString(5, txtPrecioT.getText());
        ps.setString(6,txtTel.getText());
        ps.setString(7,txtID.getText());
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Actualizacion excitosa");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error de Actualizacion  " +e.getMessage());
    }
}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCporU;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMatprim;
    private javax.swing.JTextField txtNcom;
    private javax.swing.JTextField txtNlegal;
    private javax.swing.JTextField txtPrecioT;
    private javax.swing.JTextField txtPrecioU;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
